[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "monster-genitalia-randomizer"
version = "1.0.0a3"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.0.0",
    "PySide6",
    "platformdirs",
    "py7zr",
    "tomlkit",
    "rarfile",
    "pydantic-settings"
]

[tool.hatch.build.targets.wheel]
packages = ["mgr"]
